# Generated by Django 5.2.2 on 2025-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "default_related_name": "custom_users",
                "ordering": ["-date_joined"],
                "verbose_name": "custom user",
                "verbose_name_plural": "custom users",
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="email_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["last_name", "first_name"], name="name_idx"),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_user_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username"
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="custom_users",
        ),
    ]
