# Generated by Django 5.2.2 on 2025-06-12 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("can_change_status", "Может изменять статус рассылки")
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-time"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-id"],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(fields=["status"], name="mailings_ma_status_c690eb_idx"),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["mailing", "time"], name="mailings_ma_mailing_23ddec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("owner", "subject"), name="unique_owner_message_subject"
            ),
        ),
    ]
